library(shiny)
library(shinythemes)
library(ggplot2)
library(magrittr)
library(DT)
library(reactable)
library(shinyWidgets)
library(shinysky)
library(tidyverse)
library(httr)
library(stringr)
library(lubridate)
library(plotly)
library(shinydashboard)
library(caret)
library(formattable)
library(data.table)
library(plotly)
library(highcharter)
library(RColorBrewer)
library(htmltools)
library(shinyjs)
library(leaflet)
library(reshape2)
library(class)
library(FNN)

#Loading Data
fullteams = readr::read_csv("fullteams.csv")

hello = "hello"
